### ISSUE TITLE
Do not quote everything

### ISSUE THREAD

**Issue by agladysh** [FourierTransformer/ftcsv#33]
Code:

```lua
local ftcsv = require 'ftcsv'

io.stdout:write(
  ftcsv.encode(
    {
      { a = 1, b = '', c = 'foo', d = '"quoted"' };
    },
    ','
  )
)
```

Output:

```csv
"a","b","c","d"
"1","","foo","""quoted"""
```

Expected:

```csv
a,b,c,d
1,,foo,"""quoted"""
```

**Comment by FourierTransformer** [comment]
So, quoting the output is sort've how CSVs are intended to be. This could be added as an option to not include quotes on encoding.

Also, I think `"quoted"` should go to `""quoted""` rather than `"""quoted"""`. As it's usually a double quote to escape a `"`, as opposed to having one field be quoted (and properly escaped) in the output. As long as that's the case, you could probably modify the `csvLineGenerator` `outputFunc` to just not have the double quotes.

**Comment by FourierTransformer** [comment]
You were right with the triple quotes. Sorry about that. Regardless the bugfix and feature have been added on the main branch. I'll cut a new release here in a couple of days.

**Comment by FourierTransformer** [comment]
Found a small bug during testing and finally got around to fixing it. Also changed from `noQuotes` to `onlyRequiredQuotes` after realizing the old option name was a little confusing. New release 1.3.0 is out and available on luarocks!
