### ISSUE TITLE
Design a clean interface for a fixed-memory reader

### ISSUE THREAD

**Issue by FourierTransformer** [FourierTransformer/ftcsv#4]
The fixed-memory reader would return a line of parsed data at a time.

The `parseString` function already has support for starting at an arbitrary character in the input file. Some tooling would have to be put in place to load chunks of the file at a time. It will likely be easiest to continue parsing the chunk until a whole line cannot be parsed, appending the new chunk, and restart parsing at the beginning of the line while removing already parsed lines.

This should prevent having to store excessive state information (partially parsed lines) and would allow buffering a few lines worth of information. It also enforces that the minimum buffer length is greater than or equal to the maximum row size to remain parseable.

**Comment by FourierTransformer** [comment]
Work on this has started in the [parseLineIterator branch](https://github.com/FourierTransformer/ftcsv/tree/parseLineIterator) and a basic iterator based parser has been written. @Oozlum, if you have any thoughts let me know. I'm also thinking about adding a function to return just the headers and an iterator for writing chunks out, but am not sure if the latter will be too useful.

**Comment by Oozlum** [comment]
I've implemented a [chunk-based parser branch](/Oozlum/ftcsv/tree/chunk_based_parser), which allows ftcsv.parse to accept a simple iterator function as its first parameter to provide a series of string chunks to drive the parser.  If a raw CSV string, or filename is given, it loads the entire CSV content into a string and wraps it as an iterator with a single chunk.

Internally, this branch uses an iterator to parse the headers and row content, but this isn't exposed to the caller as I didn't want to change the API to start with.

**Comment by FourierTransformer** [comment]
That seems like an interesting approach. I dislike how people need to handle the files themselves and it's a bit odd passing an iterator to something that isn't a for loop. I think it's a bit easier for people to use an iterator and think it's a valid reason to add additional functionality. I'm probably going to go ahead with my parseLineIterator branch after writing something to extract headers.

**Comment by Oozlum** [comment]
There are three issues here:
 1. splitting files into manageable chunks;
 2. making the parser handle a stream of chunks; and
 3. giving the caller an iterator to process the output.

My branch, at present, is only intended to address the second issue and as much of the first as to be able to test it without changing the calling API too much. I did it this way so that I could run the existing test suite to confirm correctness and equivalence. My new parser passes all tests and I have to say I’m pleased with it.

Moving forward, if we split the file into chunks then we have to give the user a mechanism to define those chunks. That means either a number of special case options, or passing in an iterator/iterator factory. I prefer the latter approach, but there’s no reason that we can’t define standard iterators for the two common choices: line-by-line and fixed-size.

**Comment by Oozlum** [comment]
Also, passing in an iterator factory isn’t an odd thing to do. It’s given in PIL as an example of using iterators.
